language: r
sudo: false
cache: packages

after_success:
 - Rscript -e 'covr::codecov()'

env:
  global:
    - R_CHECK_ARGS="--run-dontrun --as-cran"

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: XjCNOufVyfFUl9MIW6Vh7d/lcInse0lM3Le/XAdOJLYMpqwGiVQjhbxcHU68uXSX2LmuraLA0PsXTq6Hw2ciNUFo5oqCdTkhTNRbk8S5mzZWupZzGR1JEdAtP3MlOQcRmeObzw35pEdJh4fmG7OPhq4vLCeh915oClmFYyoXBgk=
