language: r

notifications:
  slack:
    secure: ZwvL7pgs0YkqCXYMp2Mmu+qA+frsBPMmksZZQDxG9LgRHDTDMNEsyiFGKSot/yLYAbCEiWS/B+hI1Ow3f1SgbOvovjsTQVOr0tONq1Wyg44DaR637zUTVy40FXAwGTnQNTpFq7WTiwyrB+dt81svNWV/ZFpV+/vgpFF1lTp+PhM=
  email:
    on_success: change
    on_failure: change
